a = input("Digite algo: ")
print ("o tipo primitivo desse valor é: ",type(a))
print ("Só tem espaços ? ", a.isspace())
print ("É um número ?", a.isnumeric())
print ("É alfabético ?", a.isalpha())
print ("É alfanumérico ?", a.isalnum())
print ("Tem capslock ?", a.isupper())
print ("Não tem capslock ?", a.islower())
print ("Está capitalizada ?", a.istitle())

